lib: [
  "_build/install/default/lib/cbor/META"
  "_build/install/default/lib/cbor/cbor.a"
  "_build/install/default/lib/cbor/cbor.cma"
  "_build/install/default/lib/cbor/cbor.cmi"
  "_build/install/default/lib/cbor/cbor.cmt"
  "_build/install/default/lib/cbor/cbor.cmx"
  "_build/install/default/lib/cbor/cbor.cmxa"
  "_build/install/default/lib/cbor/cbor.cmxs"
  "_build/install/default/lib/cbor/cbor.ml"
  "_build/install/default/lib/cbor/dune-package"
  "_build/install/default/lib/cbor/opam"
]
doc: [
  "_build/install/default/doc/cbor/LICENSE"
]
